// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
import type { ComponentType, SVGProps } from "react";
import { AccessTimeIcon } from "./glyphs";
import { AccessoriesIcon } from "./glyphs";
import { AccountingAndFinanceIcon } from "./glyphs";
import { AccountingFinanceLegalIcon } from "./glyphs";
import { AddCameraOIcon } from "./glyphs";
import { AddCircleFIcon } from "./glyphs";
import { AddCircleOutlineIcon } from "./glyphs";
import { AddCircleIcon } from "./glyphs";
import { AddNoteDetailedOIcon } from "./glyphs";
import { AddNoteOIcon } from "./glyphs";
import { AddPersonFIcon } from "./glyphs";
import { AddPhotoOIcon } from "./glyphs";
import { AddPlaceFIcon } from "./glyphs";
import { AddPlaceOIcon } from "./glyphs";
import { AddVideoIcon } from "./glyphs";
import { AddIcon } from "./glyphs";
import { AddedFIcon } from "./glyphs";
import { AddedOIcon } from "./glyphs";
import { AdministrationAndHrIcon } from "./glyphs";
import { AdministrativeDocIcon } from "./glyphs";
import { AdvertOutlineIcon } from "./glyphs";
import { AiStarsFIcon } from "./glyphs";
import { AiStarsIcon } from "./glyphs";
import { AiIcon } from "./glyphs";
import { AirConditioningFanCoilIcon } from "./glyphs";
import { AlertCircleFIcon } from "./glyphs";
import { AlertCircleOIcon } from "./glyphs";
import { AnalogWatchIcon } from "./glyphs";
import { AnalyticsOutlineIcon } from "./glyphs";
import { AnalyticsIcon } from "./glyphs";
import { AnimalsIcon } from "./glyphs";
import { AnkleBootsIcon } from "./glyphs";
import { ApartmentOIcon } from "./glyphs";
import { ApartmentRentIcon } from "./glyphs";
import { ApartmentSellIcon } from "./glyphs";
import { ApplianceIcon } from "./glyphs";
import { ArchiveOIcon } from "./glyphs";
import { ArchiveIcon } from "./glyphs";
import { ArchwayIcon } from "./glyphs";
import { ArrowBackwardLargeOIcon } from "./glyphs";
import { ArrowBackwardOIcon } from "./glyphs";
import { ArrowDownwardLargeOIcon } from "./glyphs";
import { ArrowDownwardOIcon } from "./glyphs";
import { ArrowForwardLargeOIcon } from "./glyphs";
import { ArrowForwardIcon } from "./glyphs";
import { ArrowUpwardLargeOIcon } from "./glyphs";
import { ArrowUpwardOIcon } from "./glyphs";
import { ArticleMagnifierFIcon } from "./glyphs";
import { ArticleMagnifierIcon } from "./glyphs";
import { ArticleOutlineIcon } from "./glyphs";
import { ArticleIcon } from "./glyphs";
import { ArtificialFlowerIcon } from "./glyphs";
import { AssignmentIndFIcon } from "./glyphs";
import { AssignmentIndIcon } from "./glyphs";
import { AudioVideoIcon } from "./glyphs";
import { BabyAndToysIcon } from "./glyphs";
import { BabyIcon } from "./glyphs";
import { BackpackIcon } from "./glyphs";
import { Backward15OIcon } from "./glyphs";
import { BaguetteIcon } from "./glyphs";
import { BalconyIcon } from "./glyphs";
import { BaleTypeIcon } from "./glyphs";
import { BaleIcon } from "./glyphs";
import { BallSportsIcon } from "./glyphs";
import { BarbecueOutlineIcon } from "./glyphs";
import { BarbecueIcon } from "./glyphs";
import { BarbershopAndBeautysalonIcon } from "./glyphs";
import { BarterIcon } from "./glyphs";
import { BatchIcon } from "./glyphs";
import { BathroomAccessoriesIcon } from "./glyphs";
import { BathroomsIcon } from "./glyphs";
import { Battery50Icon } from "./glyphs";
import { BatteryChargingIcon } from "./glyphs";
import { BatteryHoriz075Icon } from "./glyphs";
import { BatteryProfileIcon } from "./glyphs";
import { BeautyAndHaircareIcon } from "./glyphs";
import { BedPillowBlanketIcon } from "./glyphs";
import { BedServiceIcon } from "./glyphs";
import { BedSheetIcon } from "./glyphs";
import { BellFIcon } from "./glyphs";
import { BellOIcon } from "./glyphs";
import { BicycleIcon } from "./glyphs";
import { BinderFIcon } from "./glyphs";
import { BinderOutlineIcon } from "./glyphs";
import { BirdsIcon } from "./glyphs";
import { BlockFIcon } from "./glyphs";
import { BlockIcon } from "./glyphs";
import { BoatIcon } from "./glyphs";
import { BoltOutlineIcon } from "./glyphs";
import { BoltIcon } from "./glyphs";
import { BookStudentLiteratureIcon } from "./glyphs";
import { BookcaseShelfIcon } from "./glyphs";
import { BookmarkBorderIcon } from "./glyphs";
import { BookmarkIcon } from "./glyphs";
import { BootsIcon } from "./glyphs";
import { BraceletIcon } from "./glyphs";
import { BriefcaseIcon } from "./glyphs";
import { BrushFIcon } from "./glyphs";
import { BrushOIcon } from "./glyphs";
import { BuffetShowcasesIcon } from "./glyphs";
import { BuildCircleIcon } from "./glyphs";
import { BuildingEquipmentIcon } from "./glyphs";
import { BuildingIcon } from "./glyphs";
import { BurgerMenuOIcon } from "./glyphs";
import { BusMetroTrainIcon } from "./glyphs";
import { BusIcon } from "./glyphs";
import { CabinetIcon } from "./glyphs";
import { CachedOIcon } from "./glyphs";
import { CafeAndRestaurantIcon } from "./glyphs";
import { CalculatorOutlineIcon } from "./glyphs";
import { CalculatorIcon } from "./glyphs";
import { CalendarDollorOutlineIcon } from "./glyphs";
import { CalendarDollorIcon } from "./glyphs";
import { CallEndFIcon } from "./glyphs";
import { CallEndOIcon } from "./glyphs";
import { CallMadeOIcon } from "./glyphs";
import { CallOIcon } from "./glyphs";
import { CallReceivedOIcon } from "./glyphs";
import { CallIcon } from "./glyphs";
import { CameraCamcodersIcon } from "./glyphs";
import { CameraFlipFIcon } from "./glyphs";
import { CameraFlipIcon } from "./glyphs";
import { CameraLoadingOIcon } from "./glyphs";
import { CameraLoadingIcon } from "./glyphs";
import { CameraOIcon } from "./glyphs";
import { CameraOffOIcon } from "./glyphs";
import { CameraOffIcon } from "./glyphs";
import { CameraIcon } from "./glyphs";
import { CampingOutdoorIcon } from "./glyphs";
import { CancelFIcon } from "./glyphs";
import { CancelIcon } from "./glyphs";
import { CapacityIcon } from "./glyphs";
import { CapsuleIcon } from "./glyphs";
import { CarAmenityFIcon } from "./glyphs";
import { CarAmenityIcon } from "./glyphs";
import { CarAndMotorIcon } from "./glyphs";
import { CarBodyFIcon } from "./glyphs";
import { CarBodyIcon } from "./glyphs";
import { CarDocumentsFIcon } from "./glyphs";
import { CarDocumentsIcon } from "./glyphs";
import { CarElectronicsFIcon } from "./glyphs";
import { CarEngineFIcon } from "./glyphs";
import { CarEngineIcon } from "./glyphs";
import { CarEquipmentFIcon } from "./glyphs";
import { CarEquipmentIcon } from "./glyphs";
import { CarFIcon } from "./glyphs";
import { CarHydraulicsFIcon } from "./glyphs";
import { CarHydraulicsIcon } from "./glyphs";
import { CarInspectedIcon } from "./glyphs";
import { CarInspectionIcon } from "./glyphs";
import { CarOIcon } from "./glyphs";
import { CarOptionsFIcon } from "./glyphs";
import { CarOptionsIcon } from "./glyphs";
import { CarSafetyFIcon } from "./glyphs";
import { CarSafetyIcon } from "./glyphs";
import { CarTiresFIcon } from "./glyphs";
import { CarTiresIcon } from "./glyphs";
import { CareHealthBeautyIcon } from "./glyphs";
import { CarouselIndicatorFIcon } from "./glyphs";
import { CarouselIndicatorOIcon } from "./glyphs";
import { CarpetDimensionsIcon } from "./glyphs";
import { CarpetMoquetteIcon } from "./glyphs";
import { CarpetIcon } from "./glyphs";
import { CarsIcon } from "./glyphs";
import { CartFIcon } from "./glyphs";
import { CartOIcon } from "./glyphs";
import { CatBusinessesIcon } from "./glyphs";
import { CatElectronicDevicesIcon } from "./glyphs";
import { CatServicesIcon } from "./glyphs";
import { CatVehiclesIcon } from "./glyphs";
import { CatIcon } from "./glyphs";
import { CateringIcon } from "./glyphs";
import { CctvIcon } from "./glyphs";
import { ChairBenchIcon } from "./glyphs";
import { ChairOfficeFIcon } from "./glyphs";
import { ChairOfficeOIcon } from "./glyphs";
import { ChairsIcon } from "./glyphs";
import { ChandelierIcon } from "./glyphs";
import { ChandeliersIcon } from "./glyphs";
import { ChartIcon } from "./glyphs";
import { ChatBotOIcon } from "./glyphs";
import { ChatBotIcon } from "./glyphs";
import { ChatBubbleFIcon } from "./glyphs";
import { ChatBubbleIcon } from "./glyphs";
import { ChatDoubleIcon } from "./glyphs";
import { ChatSparklesIcon } from "./glyphs";
import { CheckCircleFIcon } from "./glyphs";
import { CheckCircleIcon } from "./glyphs";
import { CheckOIcon } from "./glyphs";
import { CheckedFIcon } from "./glyphs";
import { CheckedIcon } from "./glyphs";
import { ChevronDownIcon } from "./glyphs";
import { ChildCarSeatIcon } from "./glyphs";
import { ChildrensClothingAndShoeIcon } from "./glyphs";
import { ChildrensFurnitureIcon } from "./glyphs";
import { CircleNightModeFIcon } from "./glyphs";
import { CircleNightModeOIcon } from "./glyphs";
import { CircleOIcon } from "./glyphs";
import { ClassicIcon } from "./glyphs";
import { CleaningSuppliesIcon } from "./glyphs";
import { CleaningIcon } from "./glyphs";
import { ClipboardFIcon } from "./glyphs";
import { ClipboardIcon } from "./glyphs";
import { ClockIcon } from "./glyphs";
import { CloseIcon } from "./glyphs";
import { ClosedCaptionFIcon } from "./glyphs";
import { ClosedCaptionIcon } from "./glyphs";
import { ClothesRackIcon } from "./glyphs";
import { ClothingAndShoesIcon } from "./glyphs";
import { ClothingIcon } from "./glyphs";
import { CloudFIcon } from "./glyphs";
import { CloudOIcon } from "./glyphs";
import { CloudUploadOIcon } from "./glyphs";
import { CoffeeIcon } from "./glyphs";
import { CoinStampIcon } from "./glyphs";
import { ColorBeakerIcon } from "./glyphs";
import { CommercialRentIcon } from "./glyphs";
import { CommercialSellIcon } from "./glyphs";
import { CommunityCycleOutlineIcon } from "./glyphs";
import { CommunityCycleIcon } from "./glyphs";
import { CommunityIcon } from "./glyphs";
import { CompareOIcon } from "./glyphs";
import { CompareIcon } from "./glyphs";
import { ComputerAndItIcon } from "./glyphs";
import { ComputerAndMobileIcon } from "./glyphs";
import { ComputersIcon } from "./glyphs";
import { ConcertIcon } from "./glyphs";
import { ConditionIcon } from "./glyphs";
import { ConferenceMeetingIcon } from "./glyphs";
import { ConstructionCraftIcon } from "./glyphs";
import { ContactPhoneOIcon } from "./glyphs";
import { ContactPhoneIcon } from "./glyphs";
import { ContainerOrganizersIcon } from "./glyphs";
import { ContainersIcon } from "./glyphs";
import { ContentCopyIcon } from "./glyphs";
import { ControllerIcon } from "./glyphs";
import { CookingUtensilsIcon } from "./glyphs";
import { CosmeticsIcon } from "./glyphs";
import { CpuIcon } from "./glyphs";
import { CraftsIcon } from "./glyphs";
import { CraftsmenIcon } from "./glyphs";
import { CreditAccountOIcon } from "./glyphs";
import { CreditCardOIcon } from "./glyphs";
import { CreditCardIcon } from "./glyphs";
import { CrisisSupportIcon } from "./glyphs";
import { Crop43OIcon } from "./glyphs";
import { CropOIcon } from "./glyphs";
import { CropSquareOIcon } from "./glyphs";
import { CurtainsTableCoverIcon } from "./glyphs";
import { DecorationIcon } from "./glyphs";
import { DeleteFIcon } from "./glyphs";
import { DeleteIcon } from "./glyphs";
import { DeskIcon } from "./glyphs";
import { DesktopsIcon } from "./glyphs";
import { DetergentTissueIcon } from "./glyphs";
import { DialogFIcon } from "./glyphs";
import { DialogOIcon } from "./glyphs";
import { DiceOIcon } from "./glyphs";
import { DigitalWatchIcon } from "./glyphs";
import { DiningTableIcon } from "./glyphs";
import { DishWashingMachineIcon } from "./glyphs";
import { DishwasherIcon } from "./glyphs";
import { DivingWatersportsIcon } from "./glyphs";
import { DocFIcon } from "./glyphs";
import { DocOIcon } from "./glyphs";
import { DocO1Icon } from "./glyphs";
import { DogIcon } from "./glyphs";
import { DollorOIcon } from "./glyphs";
import { DoorIcon } from "./glyphs";
import { DownloadOIcon } from "./glyphs";
import { DressShoesIcon } from "./glyphs";
import { DrinkMakerIcon } from "./glyphs";
import { DropBoltOutlineIcon } from "./glyphs";
import { DropBoltIcon } from "./glyphs";
import { DropOutlineIcon } from "./glyphs";
import { DropIcon } from "./glyphs";
import { DrumsPercussionIcon } from "./glyphs";
import { EarnestIcon } from "./glyphs";
import { EarringsIcon } from "./glyphs";
import { EarthOIcon } from "./glyphs";
import { EditFIcon } from "./glyphs";
import { EditIcon } from "./glyphs";
import { EducationIcon } from "./glyphs";
import { EducationalIcon } from "./glyphs";
import { ElectricalIcon } from "./glyphs";
import { ElevatorIcon } from "./glyphs";
import { EmailOutlineIcon } from "./glyphs";
import { EraserOIcon } from "./glyphs";
import { EventNoteIcon } from "./glyphs";
import { EventIcon } from "./glyphs";
import { EventsSportsIcon } from "./glyphs";
import { ExchangeOutlineIcon } from "./glyphs";
import { ExchangeIcon } from "./glyphs";
import { EyeOffFIcon } from "./glyphs";
import { EyeOffIcon } from "./glyphs";
import { EyeIcon } from "./glyphs";
import { FaNumber4CircleOIcon } from "./glyphs";
import { FaNumber5CircleOIcon } from "./glyphs";
import { FaNumber6CircleOIcon } from "./glyphs";
import { FaNumber7CircleOIcon } from "./glyphs";
import { FaNumber8CircleOIcon } from "./glyphs";
import { FaNumber9CircleOIcon } from "./glyphs";
import { FakeBadgeIcon } from "./glyphs";
import { FanVentilatorHumidifierIcon } from "./glyphs";
import { FannyPackIcon } from "./glyphs";
import { FarmAnimalsIcon } from "./glyphs";
import { FavouriteFIcon } from "./glyphs";
import { FavouriteOIcon } from "./glyphs";
import { FeedbackFIcon } from "./glyphs";
import { FigurinesIcon } from "./glyphs";
import { FileFIcon } from "./glyphs";
import { FileOIcon } from "./glyphs";
import { FilesFIcon } from "./glyphs";
import { FilesOIcon } from "./glyphs";
import { FilmIcon } from "./glyphs";
import { FilterOIcon } from "./glyphs";
import { FingerPrintOIcon } from "./glyphs";
import { FishIcon } from "./glyphs";
import { FishingIcon } from "./glyphs";
import { FlagFIcon } from "./glyphs";
import { FlagOIcon } from "./glyphs";
import { FlagWaveOIcon } from "./glyphs";
import { FlipOIcon } from "./glyphs";
import { FoodAndDrinkIcon } from "./glyphs";
import { FoodMillIcon } from "./glyphs";
import { ForSaleIcon } from "./glyphs";
import { Forward15OIcon } from "./glyphs";
import { FridgeIcon } from "./glyphs";
import { FruitIcon } from "./glyphs";
import { FullScreenOIcon } from "./glyphs";
import { FunnelOIcon } from "./glyphs";
import { FurnitureClassicIcon } from "./glyphs";
import { FurnitureWoodIcon } from "./glyphs";
import { FurnitureIcon } from "./glyphs";
import { GameConsolesAndVideoGamesIcon } from "./glyphs";
import { GardenAndLandscapingIcon } from "./glyphs";
import { GasStationIcon } from "./glyphs";
import { GavelFIcon } from "./glyphs";
import { GavelIcon } from "./glyphs";
import { GearFIcon } from "./glyphs";
import { GearOIcon } from "./glyphs";
import { GiftCertificateIcon } from "./glyphs";
import { GiftOIcon } from "./glyphs";
import { GlassIcon } from "./glyphs";
import { GuitarBassAmplifierIcon } from "./glyphs";
import { GymIcon } from "./glyphs";
import { HamburgerIcon } from "./glyphs";
import { HammerScrewdriverOIcon } from "./glyphs";
import { HammerScrewdriverIcon } from "./glyphs";
import { HandClickIcon } from "./glyphs";
import { HandbagIcon } from "./glyphs";
import { HashOIcon } from "./glyphs";
import { HdmiIcon } from "./glyphs";
import { HeadphoneFIcon } from "./glyphs";
import { HeadphoneOIcon } from "./glyphs";
import { HeadphonesIcon } from "./glyphs";
import { HealthBeautyIcon } from "./glyphs";
import { HeavyIcon } from "./glyphs";
import { HelpFIcon } from "./glyphs";
import { HelpOutlineIcon } from "./glyphs";
import { HelpIcon } from "./glyphs";
import { HerbalPillsIcon } from "./glyphs";
import { HighwayIcon } from "./glyphs";
import { HistoricalObjectsIcon } from "./glyphs";
import { HistoricalIcon } from "./glyphs";
import { HistoryIcon } from "./glyphs";
import { HobbyCollectiblesIcon } from "./glyphs";
import { HomeAreaIcon } from "./glyphs";
import { HomeCateringIcon } from "./glyphs";
import { HomeInspectionIcon } from "./glyphs";
import { HomeLightingIcon } from "./glyphs";
import { HomeOutlineIcon } from "./glyphs";
import { HomeIcon } from "./glyphs";
import { HorsesEquestrianIcon } from "./glyphs";
import { HospitalIcon } from "./glyphs";
import { HouseInspectionIcon } from "./glyphs";
import { HouseVillaRentIcon } from "./glyphs";
import { HouseVillaSellIcon } from "./glyphs";
import { ImageMultipleIcon } from "./glyphs";
import { ImageOutlineIcon } from "./glyphs";
import { IndicatorFIcon } from "./glyphs";
import { IndustrialMachineryIcon } from "./glyphs";
import { IndustrialTechnologyIcon } from "./glyphs";
import { IndustryAgricultureBusinessRentIcon } from "./glyphs";
import { IndustryAgricultureBusinessSellIcon } from "./glyphs";
import { InfoCircleFIcon } from "./glyphs";
import { InfoCircleOIcon } from "./glyphs";
import { InfoCircleO1Icon } from "./glyphs";
import { InfoFIcon } from "./glyphs";
import { InfoOIcon } from "./glyphs";
import { InfoOutlineIcon } from "./glyphs";
import { InspectIcon } from "./glyphs";
import { InstallmentSaleIcon } from "./glyphs";
import { InventoryIcon } from "./glyphs";
import { IranMapIcon } from "./glyphs";
import { IrancellIcon } from "./glyphs";
import { JacuzziOutlineIcon } from "./glyphs";
import { JacuzziIcon } from "./glyphs";
import { JanitorialCleaningIcon } from "./glyphs";
import { JewelryAndWatchesIcon } from "./glyphs";
import { JewelryAnkletIcon } from "./glyphs";
import { JewelrySetIcon } from "./glyphs";
import { JewelryIcon } from "./glyphs";
import { JuicersIcon } from "./glyphs";
import { KarnamehFIcon } from "./glyphs";
import { KeyboardArrowLeftFIcon } from "./glyphs";
import { KeyboardArrowLeftLargeOIcon } from "./glyphs";
import { KeyboardArrowLeftIcon } from "./glyphs";
import { KeyboardArrowRightFIcon } from "./glyphs";
import { KeyboardArrowRightLargeOIcon } from "./glyphs";
import { KeyboardArrowRightIcon } from "./glyphs";
import { KeyboardArrowUpOIcon } from "./glyphs";
import { KitchenUtensilsIcon } from "./glyphs";
import { LadderCollectionFIcon } from "./glyphs";
import { LadderCollectionIcon } from "./glyphs";
import { LadderGroupIcon } from "./glyphs";
import { LadderIcon } from "./glyphs";
import { LampOIcon } from "./glyphs";
import { LampsIcon } from "./glyphs";
import { LampshadeIcon } from "./glyphs";
import { LanIcon } from "./glyphs";
import { LaptopsIcon } from "./glyphs";
import { LaunchIcon } from "./glyphs";
import { LeisureHobbiesToysIcon } from "./glyphs";
import { LightBulbIcon } from "./glyphs";
import { LightIcon } from "./glyphs";
import { LinkIcon } from "./glyphs";
import { LiteraryIcon } from "./glyphs";
import { LoafersIcon } from "./glyphs";
import { LocalShippingFIcon } from "./glyphs";
import { LocalShippingOIcon } from "./glyphs";
import { LockFIcon } from "./glyphs";
import { LockIcon } from "./glyphs";
import { LogInOIcon } from "./glyphs";
import { LogoutIcon } from "./glyphs";
import { LostAndFoundIcon } from "./glyphs";
import { LostAnimalsIcon } from "./glyphs";
import { LostThingsIcon } from "./glyphs";
import { LumbarPillowIcon } from "./glyphs";
import { MagazinesIcon } from "./glyphs";
import { MagnifierSparklesIcon } from "./glyphs";
import { MailFIcon } from "./glyphs";
import { ManAndWomanIcon } from "./glyphs";
import { ManIcon } from "./glyphs";
import { MapFIcon } from "./glyphs";
import { MapMarkerIcon } from "./glyphs";
import { MapOIcon } from "./glyphs";
import { MatIcon } from "./glyphs";
import { MaterialIcon } from "./glyphs";
import { MathOutlineIcon } from "./glyphs";
import { MathIcon } from "./glyphs";
import { MattressIcon } from "./glyphs";
import { MciIcon } from "./glyphs";
import { MediaAdvertisingIcon } from "./glyphs";
import { MedicalEquipmentIcon } from "./glyphs";
import { MedicalIcon } from "./glyphs";
import { MelangeOIcon } from "./glyphs";
import { MemoryIcon } from "./glyphs";
import { MetroIcon } from "./glyphs";
import { MicFIcon } from "./glyphs";
import { MicOIcon } from "./glyphs";
import { MinusOIcon } from "./glyphs";
import { MirrorIcon } from "./glyphs";
import { MobileFriendlyOIcon } from "./glyphs";
import { MobileInspectionIcon } from "./glyphs";
import { MobileOIcon } from "./glyphs";
import { MobilePhonesIcon } from "./glyphs";
import { MobileTabletAccessoriesIcon } from "./glyphs";
import { MobileTabletIcon } from "./glyphs";
import { ModemAndNetworkEquipmentIcon } from "./glyphs";
import { ModemIcon } from "./glyphs";
import { MoneyBillsIcon } from "./glyphs";
import { MoneyIcon } from "./glyphs";
import { MopedFIcon } from "./glyphs";
import { MopedOIcon } from "./glyphs";
import { MoquetteIcon } from "./glyphs";
import { MoreHorizontalOIcon } from "./glyphs";
import { MorePlaceFIcon } from "./glyphs";
import { MorePlaceOIcon } from "./glyphs";
import { MoreVerticalOIcon } from "./glyphs";
import { MosqueIcon } from "./glyphs";
import { MotorcyclesIcon } from "./glyphs";
import { MouseThickOIcon } from "./glyphs";
import { MouseThinOIcon } from "./glyphs";
import { MoviesAndMusicIcon } from "./glyphs";
import { Mp3PlayerIcon } from "./glyphs";
import { MusicalInstrumentsIcon } from "./glyphs";
import { MyLocationOIcon } from "./glyphs";
import { NaturalPlantsIcon } from "./glyphs";
import { NearbyFIcon } from "./glyphs";
import { NearbyOIcon } from "./glyphs";
import { NecklaceIcon } from "./glyphs";
import { NightModeFIcon } from "./glyphs";
import { NightModeOIcon } from "./glyphs";
import { NintendoIcon } from "./glyphs";
import { Num1Icon } from "./glyphs";
import { Num2Icon } from "./glyphs";
import { Num3Icon } from "./glyphs";
import { OfficeDecorationIcon } from "./glyphs";
import { OfficeRentIcon } from "./glyphs";
import { OfficeSellIcon } from "./glyphs";
import { OfficesIcon } from "./glyphs";
import { OriginalBadgeIcon } from "./glyphs";
import { OtherAppliancesIcon } from "./glyphs";
import { OvenBakingAppliancesIcon } from "./glyphs";
import { PaintingsPictureIcon } from "./glyphs";
import { PaletteIcon } from "./glyphs";
import { PaperDeedIcon } from "./glyphs";
import { PaperclipThickOIcon } from "./glyphs";
import { PaperclipThinOIcon } from "./glyphs";
import { ParkingLotIcon } from "./glyphs";
import { ParkingIcon } from "./glyphs";
import { PartnershipIcon } from "./glyphs";
import { PartsAccessoriesIcon } from "./glyphs";
import { PartsAndAccessoriesIcon } from "./glyphs";
import { PauseOIcon } from "./glyphs";
import { PauseIcon } from "./glyphs";
import { PaymentOutlineIcon } from "./glyphs";
import { PaymentIcon } from "./glyphs";
import { PerfumesIcon } from "./glyphs";
import { PersonAddIcon } from "./glyphs";
import { PersonFIcon } from "./glyphs";
import { PersonIcon } from "./glyphs";
import { PersonalToysIcon } from "./glyphs";
import { PhoneDeskIcon } from "./glyphs";
import { PhotoFIcon } from "./glyphs";
import { PhotoLibraryFIcon } from "./glyphs";
import { PhotoOIcon } from "./glyphs";
import { PianoKeyboardIcon } from "./glyphs";
import { PictorialCarpetIcon } from "./glyphs";
import { PinFIcon } from "./glyphs";
import { PinMapFIcon } from "./glyphs";
import { PinOIcon } from "./glyphs";
import { PinTiltFIcon } from "./glyphs";
import { PinVariantIcon } from "./glyphs";
import { PlaceFIcon } from "./glyphs";
import { PlayFIcon } from "./glyphs";
import { PlayOIcon } from "./glyphs";
import { PlayStationIcon } from "./glyphs";
import { PlotOldIcon } from "./glyphs";
import { PoiIcon } from "./glyphs";
import { PoliceOutlineIcon } from "./glyphs";
import { PoliceIcon } from "./glyphs";
import { PoolIcon } from "./glyphs";
import { PostFeedbackIcon } from "./glyphs";
import { PotKettleIcon } from "./glyphs";
import { PresellIcon } from "./glyphs";
import { PrinterScanerCopierIcon } from "./glyphs";
import { PuzzleOIcon } from "./glyphs";
import { PuzzleSparklesFIcon } from "./glyphs";
import { PuzzleSparklesIcon } from "./glyphs";
import { PuzzleIcon } from "./glyphs";
import { PwaIcon } from "./glyphs";
import { RamIcon } from "./glyphs";
import { RangeHoodIcon } from "./glyphs";
import { ReadOIcon } from "./glyphs";
import { RealEstateFIcon } from "./glyphs";
import { RealEstateServicesIcon } from "./glyphs";
import { ReceivingHandIcon } from "./glyphs";
import { RefreshIcon } from "./glyphs";
import { RefrigeratorFreezerIcon } from "./glyphs";
import { ReligiousIcon } from "./glyphs";
import { RemainingTimeOIcon } from "./glyphs";
import { RemoveCircleFIcon } from "./glyphs";
import { RemoveCircleOIcon } from "./glyphs";
import { RemoveIcon } from "./glyphs";
import { RenewOIcon } from "./glyphs";
import { RentalIcon } from "./glyphs";
import { ReplyOIcon } from "./glyphs";
import { ReplyIcon } from "./glyphs";
import { ReportFIcon } from "./glyphs";
import { ReportIcon } from "./glyphs";
import { ReptileIcon } from "./glyphs";
import { ResearchIcon } from "./glyphs";
import { ResidentialRentIcon } from "./glyphs";
import { ResidentialSellIcon } from "./glyphs";
import { RestaurantIcon } from "./glyphs";
import { ResumeOIcon } from "./glyphs";
import { ResumeIcon } from "./glyphs";
import { RhinestonesIcon } from "./glyphs";
import { RideSharingIcon } from "./glyphs";
import { RightelIcon } from "./glyphs";
import { RingIcon } from "./glyphs";
import { RodentsRabbitsIcon } from "./glyphs";
import { RoleBrushFIcon } from "./glyphs";
import { RoleBrushOIcon } from "./glyphs";
import { Rotate90OIcon } from "./glyphs";
import { RotateLeftOIcon } from "./glyphs";
import { RotateRightOIcon } from "./glyphs";
import { RubberCarpetIcon } from "./glyphs";
import { RugsWoolenClothIcon } from "./glyphs";
import { SalesMarketingIcon } from "./glyphs";
import { SandalsIcon } from "./glyphs";
import { SaunaOutlineIcon } from "./glyphs";
import { SaunaIcon } from "./glyphs";
import { SchoolOutlineIcon } from "./glyphs";
import { SchoolIcon } from "./glyphs";
import { ScissorsIcon } from "./glyphs";
import { ScreenSizeIcon } from "./glyphs";
import { ScreenshotIcon } from "./glyphs";
import { ScriptTextIcon } from "./glyphs";
import { SdIcon } from "./glyphs";
import { SearchLargeOIcon } from "./glyphs";
import { SearchOIcon } from "./glyphs";
import { SendFIcon } from "./glyphs";
import { SendIcon } from "./glyphs";
import { SettingOIcon } from "./glyphs";
import { SewingAccessoriesIcon } from "./glyphs";
import { SewingKnittingIcon } from "./glyphs";
import { SewingMachineIcon } from "./glyphs";
import { ShakingHandsIcon } from "./glyphs";
import { Share2FIcon } from "./glyphs";
import { Share2OIcon } from "./glyphs";
import { ShareOIcon } from "./glyphs";
import { ShareIcon } from "./glyphs";
import { ShatelIcon } from "./glyphs";
import { ShieldCheckCircleOIcon } from "./glyphs";
import { ShieldCheckCircleIcon } from "./glyphs";
import { ShieldCheckOIcon } from "./glyphs";
import { ShieldCheckIcon } from "./glyphs";
import { ShieldPhoneOIcon } from "./glyphs";
import { ShieldPhoneIcon } from "./glyphs";
import { ShoeRackDrawerIcon } from "./glyphs";
import { ShoesBeltBagIcon } from "./glyphs";
import { ShopAndCashIcon } from "./glyphs";
import { ShopRentIcon } from "./glyphs";
import { ShopRestaurantIcon } from "./glyphs";
import { ShopSellIcon } from "./glyphs";
import { ShoppingIcon } from "./glyphs";
import { ShoulderBagIcon } from "./glyphs";
import { SideTableIcon } from "./glyphs";
import { SimCardIcon } from "./glyphs";
import { SimHolderIcon } from "./glyphs";
import { SimIcon } from "./glyphs";
import { SkinCareIcon } from "./glyphs";
import { SkullFIcon } from "./glyphs";
import { SkullOIcon } from "./glyphs";
import { SleepGoodsIcon } from "./glyphs";
import { SlippersIcon } from "./glyphs";
import { SmartWatchIcon } from "./glyphs";
import { SmartphoneIcon } from "./glyphs";
import { SmsFIcon } from "./glyphs";
import { SmsOIcon } from "./glyphs";
import { SneakersIcon } from "./glyphs";
import { SnowflakeIcon } from "./glyphs";
import { SocialAndroidIcon } from "./glyphs";
import { SocialAparatIcon } from "./glyphs";
import { SocialAppleIcon } from "./glyphs";
import { SocialCafebazaarTypeIcon } from "./glyphs";
import { SocialDivarIcon } from "./glyphs";
import { SocialFacebookFIcon } from "./glyphs";
import { SocialFacebookIcon } from "./glyphs";
import { SocialGithubHeadIcon } from "./glyphs";
import { SocialGitlabIcon } from "./glyphs";
import { SocialInstagramFillIcon } from "./glyphs";
import { SocialInstagramIcon } from "./glyphs";
import { SocialKarnamehBadgeIcon } from "./glyphs";
import { SocialKarnamehCheckIcon } from "./glyphs";
import { SocialKarnamehIcon } from "./glyphs";
import { SocialLinkedinInvertedIcon } from "./glyphs";
import { SocialLinkedinIcon } from "./glyphs";
import { SocialMediumIcon } from "./glyphs";
import { SocialSonnatMediumIcon } from "./glyphs";
import { SocialSonnatThickIcon } from "./glyphs";
import { SocialSonnatThinIcon } from "./glyphs";
import { SocialTelegramIcon } from "./glyphs";
import { SocialTwitterIcon } from "./glyphs";
import { SocialVirgoolIcon } from "./glyphs";
import { SofaIcon } from "./glyphs";
import { Sofa1Icon } from "./glyphs";
import { SortAscendingIcon } from "./glyphs";
import { SortDescendingIcon } from "./glyphs";
import { SortIcon } from "./glyphs";
import { SparklesFIcon } from "./glyphs";
import { SpeakerDownFIcon } from "./glyphs";
import { SpeakerMuteFIcon } from "./glyphs";
import { SpeakerOffFIcon } from "./glyphs";
import { SpeakerUpFIcon } from "./glyphs";
import { SpeedometerIcon } from "./glyphs";
import { SportBagIcon } from "./glyphs";
import { SportLeisureIcon } from "./glyphs";
import { SportIcon } from "./glyphs";
import { StaircaseIcon } from "./glyphs";
import { StairsIcon } from "./glyphs";
import { StarFIcon } from "./glyphs";
import { StarHalfLeftOIcon } from "./glyphs";
import { StarHalfRightOIcon } from "./glyphs";
import { StarOIcon } from "./glyphs";
import { StationeryIcon } from "./glyphs";
import { SteamIronIcon } from "./glyphs";
import { StereoSurroundIcon } from "./glyphs";
import { StethoscopeIcon } from "./glyphs";
import { StopWatchFIcon } from "./glyphs";
import { StopWatchIcon } from "./glyphs";
import { StoreFIcon } from "./glyphs";
import { StoreOIcon } from "./glyphs";
import { StovesHeatersFireplacesIcon } from "./glyphs";
import { StreetSignIcon } from "./glyphs";
import { StrollersAndAccessoriesIcon } from "./glyphs";
import { SuitcaseOIcon } from "./glyphs";
import { SuiteApartmentIcon } from "./glyphs";
import { SunnyIcon } from "./glyphs";
import { SupportAgentIcon } from "./glyphs";
import { SupportIcon } from "./glyphs";
import { SyringeIcon } from "./glyphs";
import { TableclothsIcon } from "./glyphs";
import { TabletOIcon } from "./glyphs";
import { TabletIcon } from "./glyphs";
import { TagCheckCircleIcon } from "./glyphs";
import { TagOutlineIcon } from "./glyphs";
import { TagIcon } from "./glyphs";
import { TaxiIcon } from "./glyphs";
import { TeachingIcon } from "./glyphs";
import { TelephoneIcon } from "./glyphs";
import { TemporaryRentIcon } from "./glyphs";
import { TemporaryShelterIcon } from "./glyphs";
import { TermsFIcon } from "./glyphs";
import { TermsIcon } from "./glyphs";
import { TextMessageFIcon } from "./glyphs";
import { TextSmsOutlineIcon } from "./glyphs";
import { TextureIcon } from "./glyphs";
import { TheatreAndCinemaIcon } from "./glyphs";
import { ThermometerIcon } from "./glyphs";
import { ThumbDownFIcon } from "./glyphs";
import { ThumbDownOIcon } from "./glyphs";
import { ThumbUpFIcon } from "./glyphs";
import { ThumbUpOIcon } from "./glyphs";
import { TicketIcon } from "./glyphs";
import { TicketsSportsIcon } from "./glyphs";
import { TimerIcon } from "./glyphs";
import { TocIcon } from "./glyphs";
import { TomanSignIcon } from "./glyphs";
import { ToolboxIcon } from "./glyphs";
import { TooltipImageFIcon } from "./glyphs";
import { TooltipImageOIcon } from "./glyphs";
import { TooltipTextFIcon } from "./glyphs";
import { TooltipTextOIcon } from "./glyphs";
import { TraditionalIcon } from "./glyphs";
import { TrainingIcon } from "./glyphs";
import { TranslateIcon } from "./glyphs";
import { TransportIcon } from "./glyphs";
import { TransportationIcon } from "./glyphs";
import { TrashFIcon } from "./glyphs";
import { TrashOIcon } from "./glyphs";
import { TravelPackagesIcon } from "./glyphs";
import { TreesIcon } from "./glyphs";
import { TrendingUpIcon } from "./glyphs";
import { TriangleTopFIcon } from "./glyphs";
import { TuneIcon } from "./glyphs";
import { TvProjectorIcon } from "./glyphs";
import { TvStandIcon } from "./glyphs";
import { UmbrellaFIcon } from "./glyphs";
import { UmbrellaIcon } from "./glyphs";
import { UsbIcon } from "./glyphs";
import { VacuumsCleanerIcon } from "./glyphs";
import { VentilationCoolingHeatingIcon } from "./glyphs";
import { VerifiedBadgeFIcon } from "./glyphs";
import { VerifiedOIcon } from "./glyphs";
import { VerifiedUserIcon } from "./glyphs";
import { VideoDvdplayerIcon } from "./glyphs";
import { VideoLibraryIcon } from "./glyphs";
import { VideocamOIcon } from "./glyphs";
import { VideocamOffIcon } from "./glyphs";
import { VideocamIcon } from "./glyphs";
import { VillaIcon } from "./glyphs";
import { ViolinsIcon } from "./glyphs";
import { VirusOIcon } from "./glyphs";
import { VisibilityFIcon } from "./glyphs";
import { VoipFIcon } from "./glyphs";
import { VoipOIcon } from "./glyphs";
import { VolumeHighIcon } from "./glyphs";
import { VolumeOffIcon } from "./glyphs";
import { VolunteersIcon } from "./glyphs";
import { VrIcon } from "./glyphs";
import { WallClockIcon } from "./glyphs";
import { WalletOIcon } from "./glyphs";
import { WalletIcon } from "./glyphs";
import { WarningFIcon } from "./glyphs";
import { WarningIcon } from "./glyphs";
import { WashingCleaningIcon } from "./glyphs";
import { WashingMachineIcon } from "./glyphs";
import { WashingMachinesIcon } from "./glyphs";
import { WatchesIcon } from "./glyphs";
import { WaterCoolerRefineryIcon } from "./glyphs";
import { WaterCoolerIcon } from "./glyphs";
import { WaterHeaterPackageRadiatorIcon } from "./glyphs";
import { WcAccessoriesIcon } from "./glyphs";
import { WcIcon } from "./glyphs";
import { WifiOffIcon } from "./glyphs";
import { WifiIcon } from "./glyphs";
import { WindIcon } from "./glyphs";
import { WinterSportsIcon } from "./glyphs";
import { WomanIcon } from "./glyphs";
import { WorkEquipmentIcon } from "./glyphs";
import { WorkspaceIcon } from "./glyphs";
import { WorldMapIcon } from "./glyphs";
import { WrenchOutlineIcon } from "./glyphs";
import { WrenchIcon } from "./glyphs";
import { XboxIcon } from "./glyphs";
import { YarnLightsIcon } from "./glyphs";
import { ZoomInIcon } from "./glyphs";
import { ZoomOutIcon } from "./glyphs";
import type { IconName } from "./icon-names";

export const iconRegistry: Record<IconName, ComponentType<SVGProps<SVGSVGElement>>> = {
  "access-time": AccessTimeIcon,
  "accessories": AccessoriesIcon,
  "accounting-and-finance": AccountingAndFinanceIcon,
  "accounting-finance-legal": AccountingFinanceLegalIcon,
  "add-camera-o": AddCameraOIcon,
  "add-circle-f": AddCircleFIcon,
  "add-circle-outline": AddCircleOutlineIcon,
  "add-circle": AddCircleIcon,
  "add-note-detailed-o": AddNoteDetailedOIcon,
  "add-note-o": AddNoteOIcon,
  "add-person-f": AddPersonFIcon,
  "add-photo-o": AddPhotoOIcon,
  "add-place-f": AddPlaceFIcon,
  "add-place-o": AddPlaceOIcon,
  "add-video": AddVideoIcon,
  "add": AddIcon,
  "added-f": AddedFIcon,
  "added-o": AddedOIcon,
  "administration-and-hr": AdministrationAndHrIcon,
  "administrative-doc": AdministrativeDocIcon,
  "advert-outline": AdvertOutlineIcon,
  "ai-stars-f": AiStarsFIcon,
  "ai-stars": AiStarsIcon,
  "ai": AiIcon,
  "air-conditioning-fan-coil": AirConditioningFanCoilIcon,
  "alert-circle-f": AlertCircleFIcon,
  "alert-circle-o": AlertCircleOIcon,
  "analog-watch": AnalogWatchIcon,
  "analytics-outline": AnalyticsOutlineIcon,
  "analytics": AnalyticsIcon,
  "animals": AnimalsIcon,
  "ankle-boots": AnkleBootsIcon,
  "apartment-o": ApartmentOIcon,
  "apartment-rent": ApartmentRentIcon,
  "apartment-sell": ApartmentSellIcon,
  "appliance": ApplianceIcon,
  "archive-o": ArchiveOIcon,
  "archive": ArchiveIcon,
  "archway": ArchwayIcon,
  "arrow-backward-large-o": ArrowBackwardLargeOIcon,
  "arrow-backward-o": ArrowBackwardOIcon,
  "arrow-downward-large-o": ArrowDownwardLargeOIcon,
  "arrow-downward-o": ArrowDownwardOIcon,
  "arrow-forward-large-o": ArrowForwardLargeOIcon,
  "arrow-forward": ArrowForwardIcon,
  "arrow-upward-large-o": ArrowUpwardLargeOIcon,
  "arrow-upward-o": ArrowUpwardOIcon,
  "article-magnifier-f": ArticleMagnifierFIcon,
  "article-magnifier": ArticleMagnifierIcon,
  "article-outline": ArticleOutlineIcon,
  "article": ArticleIcon,
  "artificial-flower": ArtificialFlowerIcon,
  "assignment-ind-f": AssignmentIndFIcon,
  "assignment-ind": AssignmentIndIcon,
  "audio-video": AudioVideoIcon,
  "baby-and-toys": BabyAndToysIcon,
  "baby": BabyIcon,
  "backpack": BackpackIcon,
  "backward-15-o": Backward15OIcon,
  "baguette": BaguetteIcon,
  "balcony": BalconyIcon,
  "bale-type": BaleTypeIcon,
  "bale": BaleIcon,
  "ball-sports": BallSportsIcon,
  "barbecue-outline": BarbecueOutlineIcon,
  "barbecue": BarbecueIcon,
  "barbershop-and-beautysalon": BarbershopAndBeautysalonIcon,
  "barter": BarterIcon,
  "batch": BatchIcon,
  "bathroom-accessories": BathroomAccessoriesIcon,
  "bathrooms": BathroomsIcon,
  "battery-50": Battery50Icon,
  "battery-charging": BatteryChargingIcon,
  "battery-horiz-075": BatteryHoriz075Icon,
  "battery-profile": BatteryProfileIcon,
  "beauty-and-haircare": BeautyAndHaircareIcon,
  "bed-pillow-blanket": BedPillowBlanketIcon,
  "bed-service": BedServiceIcon,
  "bed-sheet": BedSheetIcon,
  "bell-f": BellFIcon,
  "bell-o": BellOIcon,
  "bicycle": BicycleIcon,
  "binder-f": BinderFIcon,
  "binder-outline": BinderOutlineIcon,
  "birds": BirdsIcon,
  "block-f": BlockFIcon,
  "block": BlockIcon,
  "boat": BoatIcon,
  "bolt-outline": BoltOutlineIcon,
  "bolt": BoltIcon,
  "book-student-literature": BookStudentLiteratureIcon,
  "bookcase-shelf": BookcaseShelfIcon,
  "bookmark-border": BookmarkBorderIcon,
  "bookmark": BookmarkIcon,
  "boots": BootsIcon,
  "bracelet": BraceletIcon,
  "briefcase": BriefcaseIcon,
  "brush-f": BrushFIcon,
  "brush-o": BrushOIcon,
  "buffet-showcases": BuffetShowcasesIcon,
  "build-circle": BuildCircleIcon,
  "building-equipment": BuildingEquipmentIcon,
  "building": BuildingIcon,
  "burger-menu-o": BurgerMenuOIcon,
  "bus-metro-train": BusMetroTrainIcon,
  "bus": BusIcon,
  "cabinet": CabinetIcon,
  "cached-o": CachedOIcon,
  "cafe-and-restaurant": CafeAndRestaurantIcon,
  "calculator-outline": CalculatorOutlineIcon,
  "calculator": CalculatorIcon,
  "calendar-dollor-outline": CalendarDollorOutlineIcon,
  "calendar-dollor": CalendarDollorIcon,
  "call-end-f": CallEndFIcon,
  "call-end-o": CallEndOIcon,
  "call-made-o": CallMadeOIcon,
  "call-o": CallOIcon,
  "call-received-o": CallReceivedOIcon,
  "call": CallIcon,
  "camera-camcoders": CameraCamcodersIcon,
  "camera-flip-f": CameraFlipFIcon,
  "camera-flip": CameraFlipIcon,
  "camera-loading-o": CameraLoadingOIcon,
  "camera-loading": CameraLoadingIcon,
  "camera-o": CameraOIcon,
  "camera-off-o": CameraOffOIcon,
  "camera-off": CameraOffIcon,
  "camera": CameraIcon,
  "camping-outdoor": CampingOutdoorIcon,
  "cancel-f": CancelFIcon,
  "cancel": CancelIcon,
  "capacity": CapacityIcon,
  "capsule": CapsuleIcon,
  "car-amenity-f": CarAmenityFIcon,
  "car-amenity": CarAmenityIcon,
  "car-and-motor": CarAndMotorIcon,
  "car-body-f": CarBodyFIcon,
  "car-body": CarBodyIcon,
  "car-documents-f": CarDocumentsFIcon,
  "car-documents": CarDocumentsIcon,
  "car-electronics-f": CarElectronicsFIcon,
  "car-engine-f": CarEngineFIcon,
  "car-engine": CarEngineIcon,
  "car-equipment-f": CarEquipmentFIcon,
  "car-equipment": CarEquipmentIcon,
  "car-f": CarFIcon,
  "car-hydraulics-f": CarHydraulicsFIcon,
  "car-hydraulics": CarHydraulicsIcon,
  "car-inspected": CarInspectedIcon,
  "car-inspection": CarInspectionIcon,
  "car-o": CarOIcon,
  "car-options-f": CarOptionsFIcon,
  "car-options": CarOptionsIcon,
  "car-safety-f": CarSafetyFIcon,
  "car-safety": CarSafetyIcon,
  "car-tires-f": CarTiresFIcon,
  "car-tires": CarTiresIcon,
  "care-health-beauty": CareHealthBeautyIcon,
  "carousel-indicator-f": CarouselIndicatorFIcon,
  "carousel-indicator-o": CarouselIndicatorOIcon,
  "carpet-dimensions": CarpetDimensionsIcon,
  "carpet-moquette": CarpetMoquetteIcon,
  "carpet": CarpetIcon,
  "cars": CarsIcon,
  "cart-f": CartFIcon,
  "cart-o": CartOIcon,
  "cat-businesses": CatBusinessesIcon,
  "cat-electronic-devices": CatElectronicDevicesIcon,
  "cat-services": CatServicesIcon,
  "cat-vehicles": CatVehiclesIcon,
  "cat": CatIcon,
  "catering": CateringIcon,
  "cctv": CctvIcon,
  "chair-bench": ChairBenchIcon,
  "chair-office-f": ChairOfficeFIcon,
  "chair-office-o": ChairOfficeOIcon,
  "chairs": ChairsIcon,
  "chandelier": ChandelierIcon,
  "chandeliers": ChandeliersIcon,
  "chart": ChartIcon,
  "chat-bot-o": ChatBotOIcon,
  "chat-bot": ChatBotIcon,
  "chat-bubble-f": ChatBubbleFIcon,
  "chat-bubble": ChatBubbleIcon,
  "chat-double": ChatDoubleIcon,
  "chat-sparkles": ChatSparklesIcon,
  "check-circle-f": CheckCircleFIcon,
  "check-circle": CheckCircleIcon,
  "check-o": CheckOIcon,
  "checked-f": CheckedFIcon,
  "checked": CheckedIcon,
  "chevron-down": ChevronDownIcon,
  "child-car-seat": ChildCarSeatIcon,
  "childrens-clothing-and-shoe": ChildrensClothingAndShoeIcon,
  "childrens-furniture": ChildrensFurnitureIcon,
  "circle-night-mode-f": CircleNightModeFIcon,
  "circle-night-mode-o": CircleNightModeOIcon,
  "circle-o": CircleOIcon,
  "classic": ClassicIcon,
  "cleaning-supplies": CleaningSuppliesIcon,
  "cleaning": CleaningIcon,
  "clipboard-f": ClipboardFIcon,
  "clipboard": ClipboardIcon,
  "clock": ClockIcon,
  "close": CloseIcon,
  "closed-caption-f": ClosedCaptionFIcon,
  "closed-caption": ClosedCaptionIcon,
  "clothes-rack": ClothesRackIcon,
  "clothing-and-shoes": ClothingAndShoesIcon,
  "clothing": ClothingIcon,
  "cloud-f": CloudFIcon,
  "cloud-o": CloudOIcon,
  "cloud-upload-o": CloudUploadOIcon,
  "coffee": CoffeeIcon,
  "coin-stamp": CoinStampIcon,
  "color-beaker": ColorBeakerIcon,
  "commercial-rent": CommercialRentIcon,
  "commercial-sell": CommercialSellIcon,
  "community-cycle-outline": CommunityCycleOutlineIcon,
  "community-cycle": CommunityCycleIcon,
  "community": CommunityIcon,
  "compare-o": CompareOIcon,
  "compare": CompareIcon,
  "computer-and-it": ComputerAndItIcon,
  "computer-and-mobile": ComputerAndMobileIcon,
  "computers": ComputersIcon,
  "concert": ConcertIcon,
  "condition": ConditionIcon,
  "conference-meeting": ConferenceMeetingIcon,
  "construction-craft": ConstructionCraftIcon,
  "contact-phone-o": ContactPhoneOIcon,
  "contact-phone": ContactPhoneIcon,
  "container-organizers": ContainerOrganizersIcon,
  "containers": ContainersIcon,
  "content-copy": ContentCopyIcon,
  "controller": ControllerIcon,
  "cooking-utensils": CookingUtensilsIcon,
  "cosmetics": CosmeticsIcon,
  "cpu": CpuIcon,
  "crafts": CraftsIcon,
  "craftsmen": CraftsmenIcon,
  "credit-account-o": CreditAccountOIcon,
  "credit-card-o": CreditCardOIcon,
  "credit-card": CreditCardIcon,
  "crisis-support": CrisisSupportIcon,
  "crop-4-3-o": Crop43OIcon,
  "crop-o": CropOIcon,
  "crop-square-o": CropSquareOIcon,
  "curtains-table-cover": CurtainsTableCoverIcon,
  "decoration": DecorationIcon,
  "delete-f": DeleteFIcon,
  "delete": DeleteIcon,
  "desk": DeskIcon,
  "desktops": DesktopsIcon,
  "detergent-tissue": DetergentTissueIcon,
  "dialog-f": DialogFIcon,
  "dialog-o": DialogOIcon,
  "dice-o": DiceOIcon,
  "digital-watch": DigitalWatchIcon,
  "dining-table": DiningTableIcon,
  "dish-washing-machine": DishWashingMachineIcon,
  "dishwasher": DishwasherIcon,
  "diving-watersports": DivingWatersportsIcon,
  "doc-f": DocFIcon,
  "doc-o": DocOIcon,
  "doc-o1": DocO1Icon,
  "dog": DogIcon,
  "dollor-o": DollorOIcon,
  "door": DoorIcon,
  "download-o": DownloadOIcon,
  "dress-shoes": DressShoesIcon,
  "drink-maker": DrinkMakerIcon,
  "drop-bolt-outline": DropBoltOutlineIcon,
  "drop-bolt": DropBoltIcon,
  "drop-outline": DropOutlineIcon,
  "drop": DropIcon,
  "drums-percussion": DrumsPercussionIcon,
  "earnest": EarnestIcon,
  "earrings": EarringsIcon,
  "earth-o": EarthOIcon,
  "edit-f": EditFIcon,
  "edit": EditIcon,
  "education": EducationIcon,
  "educational": EducationalIcon,
  "electrical": ElectricalIcon,
  "elevator": ElevatorIcon,
  "email-outline": EmailOutlineIcon,
  "eraser-o": EraserOIcon,
  "event-note": EventNoteIcon,
  "event": EventIcon,
  "events-sports": EventsSportsIcon,
  "exchange-outline": ExchangeOutlineIcon,
  "exchange": ExchangeIcon,
  "eye-off-f": EyeOffFIcon,
  "eye-off": EyeOffIcon,
  "eye": EyeIcon,
  "fa-number-4-circle-o": FaNumber4CircleOIcon,
  "fa-number-5-circle-o": FaNumber5CircleOIcon,
  "fa-number-6-circle-o": FaNumber6CircleOIcon,
  "fa-number-7-circle-o": FaNumber7CircleOIcon,
  "fa-number-8-circle-o": FaNumber8CircleOIcon,
  "fa-number-9-circle-o": FaNumber9CircleOIcon,
  "fake-badge": FakeBadgeIcon,
  "fan-ventilator-humidifier": FanVentilatorHumidifierIcon,
  "fanny-pack": FannyPackIcon,
  "farm-animals": FarmAnimalsIcon,
  "favourite-f": FavouriteFIcon,
  "favourite-o": FavouriteOIcon,
  "feedback-f": FeedbackFIcon,
  "figurines": FigurinesIcon,
  "file-f": FileFIcon,
  "file-o": FileOIcon,
  "files-f": FilesFIcon,
  "files-o": FilesOIcon,
  "film": FilmIcon,
  "filter-o": FilterOIcon,
  "finger-print-o": FingerPrintOIcon,
  "fish": FishIcon,
  "fishing": FishingIcon,
  "flag-f": FlagFIcon,
  "flag-o": FlagOIcon,
  "flag-wave-o": FlagWaveOIcon,
  "flip-o": FlipOIcon,
  "food-and-drink": FoodAndDrinkIcon,
  "food-mill": FoodMillIcon,
  "for-sale": ForSaleIcon,
  "forward-15-o": Forward15OIcon,
  "fridge": FridgeIcon,
  "fruit": FruitIcon,
  "full-screen-o": FullScreenOIcon,
  "funnel-o": FunnelOIcon,
  "furniture-classic": FurnitureClassicIcon,
  "furniture-wood": FurnitureWoodIcon,
  "furniture": FurnitureIcon,
  "game-consoles-and-video-games": GameConsolesAndVideoGamesIcon,
  "garden-and-landscaping": GardenAndLandscapingIcon,
  "gas-station": GasStationIcon,
  "gavel-f": GavelFIcon,
  "gavel": GavelIcon,
  "gear-f": GearFIcon,
  "gear-o": GearOIcon,
  "gift-certificate": GiftCertificateIcon,
  "gift-o": GiftOIcon,
  "glass": GlassIcon,
  "guitar-bass-amplifier": GuitarBassAmplifierIcon,
  "gym": GymIcon,
  "hamburger": HamburgerIcon,
  "hammer-screwdriver-o": HammerScrewdriverOIcon,
  "hammer-screwdriver": HammerScrewdriverIcon,
  "hand-click": HandClickIcon,
  "handbag": HandbagIcon,
  "hash-o": HashOIcon,
  "hdmi": HdmiIcon,
  "headphone-f": HeadphoneFIcon,
  "headphone-o": HeadphoneOIcon,
  "headphones": HeadphonesIcon,
  "health-beauty": HealthBeautyIcon,
  "heavy": HeavyIcon,
  "help-f": HelpFIcon,
  "help-outline": HelpOutlineIcon,
  "help": HelpIcon,
  "herbal-pills": HerbalPillsIcon,
  "highway": HighwayIcon,
  "historical-objects": HistoricalObjectsIcon,
  "historical": HistoricalIcon,
  "history": HistoryIcon,
  "hobby-collectibles": HobbyCollectiblesIcon,
  "home-area": HomeAreaIcon,
  "home-catering": HomeCateringIcon,
  "home-inspection": HomeInspectionIcon,
  "home-lighting": HomeLightingIcon,
  "home-outline": HomeOutlineIcon,
  "home": HomeIcon,
  "horses-equestrian": HorsesEquestrianIcon,
  "hospital": HospitalIcon,
  "house-inspection": HouseInspectionIcon,
  "house-villa-rent": HouseVillaRentIcon,
  "house-villa-sell": HouseVillaSellIcon,
  "image-multiple": ImageMultipleIcon,
  "image-outline": ImageOutlineIcon,
  "indicator-f": IndicatorFIcon,
  "industrial-machinery": IndustrialMachineryIcon,
  "industrial-technology": IndustrialTechnologyIcon,
  "industry-agriculture-business-rent": IndustryAgricultureBusinessRentIcon,
  "industry-agriculture-business-sell": IndustryAgricultureBusinessSellIcon,
  "info-circle-f": InfoCircleFIcon,
  "info-circle-o": InfoCircleOIcon,
  "info-circle-o1": InfoCircleO1Icon,
  "info-f": InfoFIcon,
  "info-o": InfoOIcon,
  "info-outline": InfoOutlineIcon,
  "inspect": InspectIcon,
  "installment-sale": InstallmentSaleIcon,
  "inventory": InventoryIcon,
  "iran-map": IranMapIcon,
  "irancell": IrancellIcon,
  "jacuzzi-outline": JacuzziOutlineIcon,
  "jacuzzi": JacuzziIcon,
  "janitorial-cleaning": JanitorialCleaningIcon,
  "jewelry-and-watches": JewelryAndWatchesIcon,
  "jewelry-anklet": JewelryAnkletIcon,
  "jewelry-set": JewelrySetIcon,
  "jewelry": JewelryIcon,
  "juicers": JuicersIcon,
  "karnameh-f": KarnamehFIcon,
  "keyboard-arrow-left-f": KeyboardArrowLeftFIcon,
  "keyboard-arrow-left-large-o": KeyboardArrowLeftLargeOIcon,
  "keyboard-arrow-left": KeyboardArrowLeftIcon,
  "keyboard-arrow-right-f": KeyboardArrowRightFIcon,
  "keyboard-arrow-right-large-o": KeyboardArrowRightLargeOIcon,
  "keyboard-arrow-right": KeyboardArrowRightIcon,
  "keyboard-arrow-up-o": KeyboardArrowUpOIcon,
  "kitchen-utensils": KitchenUtensilsIcon,
  "ladder-collection-f": LadderCollectionFIcon,
  "ladder-collection": LadderCollectionIcon,
  "ladder-group": LadderGroupIcon,
  "ladder": LadderIcon,
  "lamp-o": LampOIcon,
  "lamps": LampsIcon,
  "lampshade": LampshadeIcon,
  "lan": LanIcon,
  "laptops": LaptopsIcon,
  "launch": LaunchIcon,
  "leisure-hobbies-toys": LeisureHobbiesToysIcon,
  "light-bulb": LightBulbIcon,
  "light": LightIcon,
  "link": LinkIcon,
  "literary": LiteraryIcon,
  "loafers": LoafersIcon,
  "local-shipping-f": LocalShippingFIcon,
  "local-shipping-o": LocalShippingOIcon,
  "lock-f": LockFIcon,
  "lock": LockIcon,
  "log-in-o": LogInOIcon,
  "logout": LogoutIcon,
  "lost-and-found": LostAndFoundIcon,
  "lost-animals": LostAnimalsIcon,
  "lost-things": LostThingsIcon,
  "lumbar-pillow": LumbarPillowIcon,
  "magazines": MagazinesIcon,
  "magnifier-sparkles": MagnifierSparklesIcon,
  "mail-f": MailFIcon,
  "man-and-woman": ManAndWomanIcon,
  "man": ManIcon,
  "map-f": MapFIcon,
  "map-marker": MapMarkerIcon,
  "map-o": MapOIcon,
  "mat": MatIcon,
  "material": MaterialIcon,
  "math-outline": MathOutlineIcon,
  "math": MathIcon,
  "mattress": MattressIcon,
  "mci": MciIcon,
  "media-advertising": MediaAdvertisingIcon,
  "medical-equipment": MedicalEquipmentIcon,
  "medical": MedicalIcon,
  "melange-o": MelangeOIcon,
  "memory": MemoryIcon,
  "metro": MetroIcon,
  "mic-f": MicFIcon,
  "mic-o": MicOIcon,
  "minus-o": MinusOIcon,
  "mirror": MirrorIcon,
  "mobile-friendly-o": MobileFriendlyOIcon,
  "mobile-inspection": MobileInspectionIcon,
  "mobile-o": MobileOIcon,
  "mobile-phones": MobilePhonesIcon,
  "mobile-tablet-accessories": MobileTabletAccessoriesIcon,
  "mobile-tablet": MobileTabletIcon,
  "modem-and-network-equipment": ModemAndNetworkEquipmentIcon,
  "modem": ModemIcon,
  "money-bills": MoneyBillsIcon,
  "money": MoneyIcon,
  "moped-f": MopedFIcon,
  "moped-o": MopedOIcon,
  "moquette": MoquetteIcon,
  "more-horizontal-o": MoreHorizontalOIcon,
  "more-place-f": MorePlaceFIcon,
  "more-place-o": MorePlaceOIcon,
  "more-vertical-o": MoreVerticalOIcon,
  "mosque": MosqueIcon,
  "motorcycles": MotorcyclesIcon,
  "mouse-thick-o": MouseThickOIcon,
  "mouse-thin-o": MouseThinOIcon,
  "movies-and-music": MoviesAndMusicIcon,
  "mp3-player": Mp3PlayerIcon,
  "musical-instruments": MusicalInstrumentsIcon,
  "my-location-o": MyLocationOIcon,
  "natural-plants": NaturalPlantsIcon,
  "nearby-f": NearbyFIcon,
  "nearby-o": NearbyOIcon,
  "necklace": NecklaceIcon,
  "night-mode-f": NightModeFIcon,
  "night-mode-o": NightModeOIcon,
  "nintendo": NintendoIcon,
  "num-1": Num1Icon,
  "num-2": Num2Icon,
  "num-3": Num3Icon,
  "office-decoration": OfficeDecorationIcon,
  "office-rent": OfficeRentIcon,
  "office-sell": OfficeSellIcon,
  "offices": OfficesIcon,
  "original-badge": OriginalBadgeIcon,
  "other-appliances": OtherAppliancesIcon,
  "oven-baking-appliances": OvenBakingAppliancesIcon,
  "paintings-picture": PaintingsPictureIcon,
  "palette": PaletteIcon,
  "paper-deed": PaperDeedIcon,
  "paperclip-thick-o": PaperclipThickOIcon,
  "paperclip-thin-o": PaperclipThinOIcon,
  "parking-lot": ParkingLotIcon,
  "parking": ParkingIcon,
  "partnership": PartnershipIcon,
  "parts-accessories": PartsAccessoriesIcon,
  "parts-and-accessories": PartsAndAccessoriesIcon,
  "pause-o": PauseOIcon,
  "pause": PauseIcon,
  "payment-outline": PaymentOutlineIcon,
  "payment": PaymentIcon,
  "perfumes": PerfumesIcon,
  "person-add": PersonAddIcon,
  "person-f": PersonFIcon,
  "person": PersonIcon,
  "personal-toys": PersonalToysIcon,
  "phone-desk": PhoneDeskIcon,
  "photo-f": PhotoFIcon,
  "photo-library-f": PhotoLibraryFIcon,
  "photo-o": PhotoOIcon,
  "piano-keyboard": PianoKeyboardIcon,
  "pictorial-carpet": PictorialCarpetIcon,
  "pin-f": PinFIcon,
  "pin-map-f": PinMapFIcon,
  "pin-o": PinOIcon,
  "pin-tilt-f": PinTiltFIcon,
  "pin-variant": PinVariantIcon,
  "place-f": PlaceFIcon,
  "play-f": PlayFIcon,
  "play-o": PlayOIcon,
  "play-station": PlayStationIcon,
  "plot-old": PlotOldIcon,
  "poi": PoiIcon,
  "police-outline": PoliceOutlineIcon,
  "police": PoliceIcon,
  "pool": PoolIcon,
  "post-feedback": PostFeedbackIcon,
  "pot-kettle": PotKettleIcon,
  "presell": PresellIcon,
  "printer-scaner-copier": PrinterScanerCopierIcon,
  "puzzle-o": PuzzleOIcon,
  "puzzle-sparkles-f": PuzzleSparklesFIcon,
  "puzzle-sparkles": PuzzleSparklesIcon,
  "puzzle": PuzzleIcon,
  "pwa": PwaIcon,
  "ram": RamIcon,
  "range-hood": RangeHoodIcon,
  "read-o": ReadOIcon,
  "real-estate-f": RealEstateFIcon,
  "real-estate-services": RealEstateServicesIcon,
  "receiving-hand": ReceivingHandIcon,
  "refresh": RefreshIcon,
  "refrigerator-freezer": RefrigeratorFreezerIcon,
  "religious": ReligiousIcon,
  "remaining-time-o": RemainingTimeOIcon,
  "remove-circle-f": RemoveCircleFIcon,
  "remove-circle-o": RemoveCircleOIcon,
  "remove": RemoveIcon,
  "renew-o": RenewOIcon,
  "rental": RentalIcon,
  "reply-o": ReplyOIcon,
  "reply": ReplyIcon,
  "report-f": ReportFIcon,
  "report": ReportIcon,
  "reptile": ReptileIcon,
  "research": ResearchIcon,
  "residential-rent": ResidentialRentIcon,
  "residential-sell": ResidentialSellIcon,
  "restaurant": RestaurantIcon,
  "resume-o": ResumeOIcon,
  "resume": ResumeIcon,
  "rhinestones": RhinestonesIcon,
  "ride-sharing": RideSharingIcon,
  "rightel": RightelIcon,
  "ring": RingIcon,
  "rodents-rabbits": RodentsRabbitsIcon,
  "role-brush-f": RoleBrushFIcon,
  "role-brush-o": RoleBrushOIcon,
  "rotate-90-o": Rotate90OIcon,
  "rotate-left-o": RotateLeftOIcon,
  "rotate-right-o": RotateRightOIcon,
  "rubber-carpet": RubberCarpetIcon,
  "rugs-woolen-cloth": RugsWoolenClothIcon,
  "sales-marketing": SalesMarketingIcon,
  "sandals": SandalsIcon,
  "sauna-outline": SaunaOutlineIcon,
  "sauna": SaunaIcon,
  "school-outline": SchoolOutlineIcon,
  "school": SchoolIcon,
  "scissors": ScissorsIcon,
  "screen-size": ScreenSizeIcon,
  "screenshot": ScreenshotIcon,
  "script-text": ScriptTextIcon,
  "sd": SdIcon,
  "search-large-o": SearchLargeOIcon,
  "search-o": SearchOIcon,
  "send-f": SendFIcon,
  "send": SendIcon,
  "setting-o": SettingOIcon,
  "sewing-accessories": SewingAccessoriesIcon,
  "sewing-knitting": SewingKnittingIcon,
  "sewing-machine": SewingMachineIcon,
  "shaking-hands": ShakingHandsIcon,
  "share-2-f": Share2FIcon,
  "share-2-o": Share2OIcon,
  "share-o": ShareOIcon,
  "share": ShareIcon,
  "shatel": ShatelIcon,
  "shield-check-circle-o": ShieldCheckCircleOIcon,
  "shield-check-circle": ShieldCheckCircleIcon,
  "shield-check-o": ShieldCheckOIcon,
  "shield-check": ShieldCheckIcon,
  "shield-phone-o": ShieldPhoneOIcon,
  "shield-phone": ShieldPhoneIcon,
  "shoe-rack-drawer": ShoeRackDrawerIcon,
  "shoes-belt-bag": ShoesBeltBagIcon,
  "shop-and-cash": ShopAndCashIcon,
  "shop-rent": ShopRentIcon,
  "shop-restaurant": ShopRestaurantIcon,
  "shop-sell": ShopSellIcon,
  "shopping": ShoppingIcon,
  "shoulder-bag": ShoulderBagIcon,
  "side-table": SideTableIcon,
  "sim-card": SimCardIcon,
  "sim-holder": SimHolderIcon,
  "sim": SimIcon,
  "skin-care": SkinCareIcon,
  "skull-f": SkullFIcon,
  "skull-o": SkullOIcon,
  "sleep-goods": SleepGoodsIcon,
  "slippers": SlippersIcon,
  "smart-watch": SmartWatchIcon,
  "smartphone": SmartphoneIcon,
  "sms-f": SmsFIcon,
  "sms-o": SmsOIcon,
  "sneakers": SneakersIcon,
  "snowflake": SnowflakeIcon,
  "social-android": SocialAndroidIcon,
  "social-aparat": SocialAparatIcon,
  "social-apple": SocialAppleIcon,
  "social-cafebazaar-type": SocialCafebazaarTypeIcon,
  "social-divar": SocialDivarIcon,
  "social-facebook-f": SocialFacebookFIcon,
  "social-facebook": SocialFacebookIcon,
  "social-github-head": SocialGithubHeadIcon,
  "social-gitlab": SocialGitlabIcon,
  "social-instagram-fill": SocialInstagramFillIcon,
  "social-instagram": SocialInstagramIcon,
  "social-karnameh-badge": SocialKarnamehBadgeIcon,
  "social-karnameh-check": SocialKarnamehCheckIcon,
  "social-karnameh": SocialKarnamehIcon,
  "social-linkedin-inverted": SocialLinkedinInvertedIcon,
  "social-linkedin": SocialLinkedinIcon,
  "social-medium": SocialMediumIcon,
  "social-sonnat-medium": SocialSonnatMediumIcon,
  "social-sonnat-thick": SocialSonnatThickIcon,
  "social-sonnat-thin": SocialSonnatThinIcon,
  "social-telegram": SocialTelegramIcon,
  "social-twitter": SocialTwitterIcon,
  "social-virgool": SocialVirgoolIcon,
  "sofa": SofaIcon,
  "sofa1": Sofa1Icon,
  "sort-ascending": SortAscendingIcon,
  "sort-descending": SortDescendingIcon,
  "sort": SortIcon,
  "sparkles-f": SparklesFIcon,
  "speaker-down-f": SpeakerDownFIcon,
  "speaker-mute-f": SpeakerMuteFIcon,
  "speaker-off-f": SpeakerOffFIcon,
  "speaker-up-f": SpeakerUpFIcon,
  "speedometer": SpeedometerIcon,
  "sport-bag": SportBagIcon,
  "sport-leisure": SportLeisureIcon,
  "sport": SportIcon,
  "staircase": StaircaseIcon,
  "stairs": StairsIcon,
  "star-f": StarFIcon,
  "star-half-left-o": StarHalfLeftOIcon,
  "star-half-right-o": StarHalfRightOIcon,
  "star-o": StarOIcon,
  "stationery": StationeryIcon,
  "steam-iron": SteamIronIcon,
  "stereo-surround": StereoSurroundIcon,
  "stethoscope": StethoscopeIcon,
  "stop-watch-f": StopWatchFIcon,
  "stop-watch": StopWatchIcon,
  "store-f": StoreFIcon,
  "store-o": StoreOIcon,
  "stoves-heaters-fireplaces": StovesHeatersFireplacesIcon,
  "street-sign": StreetSignIcon,
  "strollers-and-accessories": StrollersAndAccessoriesIcon,
  "suitcase-o": SuitcaseOIcon,
  "suite-apartment": SuiteApartmentIcon,
  "sunny": SunnyIcon,
  "support-agent": SupportAgentIcon,
  "support": SupportIcon,
  "syringe": SyringeIcon,
  "tablecloths": TableclothsIcon,
  "tablet-o": TabletOIcon,
  "tablet": TabletIcon,
  "tag-check-circle": TagCheckCircleIcon,
  "tag-outline": TagOutlineIcon,
  "tag": TagIcon,
  "taxi": TaxiIcon,
  "teaching": TeachingIcon,
  "telephone": TelephoneIcon,
  "temporary-rent": TemporaryRentIcon,
  "temporary-shelter": TemporaryShelterIcon,
  "terms-f": TermsFIcon,
  "terms": TermsIcon,
  "text-message-f": TextMessageFIcon,
  "text-sms-outline": TextSmsOutlineIcon,
  "texture": TextureIcon,
  "theatre-and-cinema": TheatreAndCinemaIcon,
  "thermometer": ThermometerIcon,
  "thumb-down-f": ThumbDownFIcon,
  "thumb-down-o": ThumbDownOIcon,
  "thumb-up-f": ThumbUpFIcon,
  "thumb-up-o": ThumbUpOIcon,
  "ticket": TicketIcon,
  "tickets-sports": TicketsSportsIcon,
  "timer": TimerIcon,
  "toc": TocIcon,
  "toman-sign": TomanSignIcon,
  "toolbox": ToolboxIcon,
  "tooltip-image-f": TooltipImageFIcon,
  "tooltip-image-o": TooltipImageOIcon,
  "tooltip-text-f": TooltipTextFIcon,
  "tooltip-text-o": TooltipTextOIcon,
  "traditional": TraditionalIcon,
  "training": TrainingIcon,
  "translate": TranslateIcon,
  "transport": TransportIcon,
  "transportation": TransportationIcon,
  "trash-f": TrashFIcon,
  "trash-o": TrashOIcon,
  "travel-packages": TravelPackagesIcon,
  "trees": TreesIcon,
  "trending-up": TrendingUpIcon,
  "triangle-top-f": TriangleTopFIcon,
  "tune": TuneIcon,
  "tv-projector": TvProjectorIcon,
  "tv-stand": TvStandIcon,
  "umbrella-f": UmbrellaFIcon,
  "umbrella": UmbrellaIcon,
  "usb": UsbIcon,
  "vacuums-cleaner": VacuumsCleanerIcon,
  "ventilation-cooling-heating": VentilationCoolingHeatingIcon,
  "verified-badge-f": VerifiedBadgeFIcon,
  "verified-o": VerifiedOIcon,
  "verified-user": VerifiedUserIcon,
  "video-dvdplayer": VideoDvdplayerIcon,
  "video-library": VideoLibraryIcon,
  "videocam-o": VideocamOIcon,
  "videocam-off": VideocamOffIcon,
  "videocam": VideocamIcon,
  "villa": VillaIcon,
  "violins": ViolinsIcon,
  "virus-o": VirusOIcon,
  "visibility-f": VisibilityFIcon,
  "voip-f": VoipFIcon,
  "voip-o": VoipOIcon,
  "volume-high": VolumeHighIcon,
  "volume-off": VolumeOffIcon,
  "volunteers": VolunteersIcon,
  "vr": VrIcon,
  "wall-clock": WallClockIcon,
  "wallet-o": WalletOIcon,
  "wallet": WalletIcon,
  "warning-f": WarningFIcon,
  "warning": WarningIcon,
  "washing-cleaning": WashingCleaningIcon,
  "washing-machine": WashingMachineIcon,
  "washing-machines": WashingMachinesIcon,
  "watches": WatchesIcon,
  "water-cooler-refinery": WaterCoolerRefineryIcon,
  "water-cooler": WaterCoolerIcon,
  "water-heater-package-radiator": WaterHeaterPackageRadiatorIcon,
  "wc-accessories": WcAccessoriesIcon,
  "wc": WcIcon,
  "wifi-off": WifiOffIcon,
  "wifi": WifiIcon,
  "wind": WindIcon,
  "winter-sports": WinterSportsIcon,
  "woman": WomanIcon,
  "work-equipment": WorkEquipmentIcon,
  "workspace": WorkspaceIcon,
  "world-map": WorldMapIcon,
  "wrench-outline": WrenchOutlineIcon,
  "wrench": WrenchIcon,
  "xbox": XboxIcon,
  "yarn-lights": YarnLightsIcon,
  "zoom-in": ZoomInIcon,
  "zoom-out": ZoomOutIcon,
};
